app.py
#!/usr/bin/env python
# coding: utf-8

from flask import Flask
from views import views
import os
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

app.secret_key = os.getenv('SECRET_KEY')

@app.template_filter('round_to_decimal')
def round_to_decimal(value, decimals=0):
    try:
        return round(float(value), decimals)
    except (ValueError, TypeError):
        return value

app.register_blueprint(views)

if os.getenv('ENVIRONMENT') == "production":
    port = os.getenv('PROD_PORT')
    host = os.getenv('PROD_HOST')
    debug = False
else:
    port = os.getenv('DEV_PORT')
    host = os.getenv('DEV_HOST')
    debug = True

if __name__ == "__main__":
  app.run(debug=debug, port=port, host=host)

views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
import os
import requests
from utils.process_candidates import process_candidates
from collections import OrderedDict
from dotenv import load_dotenv
from azure.storage.blob import BlobServiceClient, BlobType
import base64

views = Blueprint("views", __name__)
load_dotenv()

## Azure Blob Storage configuration
AZURE_STORAGE_CONNECTION_STRING = os.getenv('AZURE_STORAGE_CONNECTION_STRING')
AZURE_CONTAINER_NAME = os.getenv('AZURE_CONTAINER_NAME')

@views.route("/")
@views.route("/home")
def home():
    return render_template("home.html")

@ views.route("/about")
def about():
    return render_template("about.html")

# Upload pdf files
@views.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        job_requirements = request.form.get('longText')
        session['job_requirements'] = job_requirements
        print(session['job_requirements'])

        if not job_requirements:
            flash('Job requirement is empty!')
            return redirect(url_for('views.upload'))

        uploaded_files = request.files.getlist('pdf_files')

        for file in uploaded_files:
            if file.filename != '':
                pdf_content = file.read()
                upload_to_azure(file.filename, pdf_content)
            else:
                flash('No file selected or something went wrong.')
                return redirect(url_for('views.upload'))

        flash('File uploaded successfully.')
        return redirect(url_for('views.result'))

    else:
        return render_template("upload.html")

# Upload files to Azure
def upload_to_azure(filename, content):
    blob_service_client = BlobServiceClient.from_connection_string(AZURE_STORAGE_CONNECTION_STRING)
    container_client = blob_service_client.get_container_client(AZURE_CONTAINER_NAME)

    blob_client = container_client.get_blob_client(filename)
    blob_client.upload_blob(content, blob_type=BlobType.BlockBlob)

    print(f'Successfully uploaded {filename} to Azure Blob Storage.')

# Delete files from Azure
def remove_files_from_azure():
    blob_service_client = BlobServiceClient.from_connection_string(AZURE_STORAGE_CONNECTION_STRING)
    container_client = blob_service_client.get_container_client(AZURE_CONTAINER_NAME)

    blob_list = container_client.list_blobs()

    for blob in blob_list:
        blob_client = container_client.get_blob_client(blob)
        blob_client.delete_blob()

# Get files from Azure
def get_files_from_azure():
    blob_service_client = BlobServiceClient.from_connection_string(AZURE_STORAGE_CONNECTION_STRING)
    container_client = blob_service_client.get_container_client(AZURE_CONTAINER_NAME)

    blob_list = container_client.list_blobs()

    pdf_files = []
    for blob in blob_list:
        file_name = blob.name
        download_url = f"{container_client.url}/{file_name}"
        pdf_files.append((file_name, download_url))

    return pdf_files

@views.route('/result', methods=['GET'])
def result():
    candidate_files = get_files_from_azure()

    if not candidate_files:
        flash('No result to display.')
        return redirect(url_for('views.upload'))

    candidate_filepaths = [items[1] for items in candidate_files]

    if candidate_filepaths is None:
        flash('Failed to fetch PDF files from Azure Blob Storage.')
        return redirect(url_for('views.upload'))

    if 'job_requirements' in session:
        candidate_scores = process_candidates(candidate_filepaths, session.get('job_requirements'))

    ordered_by_values = OrderedDict(sorted(candidate_scores.items(), key=lambda item: item[1], reverse=True))
    remove_files_from_azure()
    return render_template("result.html", candidate_scores=ordered_by_values)

templates/about.html
{% extends 'base.html' %} {% block title %}About{% endblock %} {% block content
%}
<section class="about-section">
  <h1>Profilyser</h1>
  <p>
    Welcome to Profilyser, your ultimate solution for job requirement analysis
    and candidate evaluation! We use advanced AI algorithms to assess job
    descriptions and resumes, generating compatibility scores for the best match
    candidates. Save time and make informed hiring decisions with Profilyser
    today!
  </p>
</section>
{% endblock %}

templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <script src="{{ url_for('static', filename='upload.js') }}"></script>
    <script src="{{ url_for('static', filename='flash.js') }}"></script>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <section class="nav-section">
    <div class="nav-title">
      <a href="{{ url_for('views.home') }}">Profilyser</a>
    </div>
    <ul class="nav-links">
      <li><a href="{{ url_for('views.home') }}">Home</a></li>
      <li><a href="{{ url_for('views.upload') }}">Upload</a></li>
      <li><a href="{{ url_for('views.result') }}">Result</a></li>
      <li><a href="{{ url_for('views.about') }}">About</a></li>
    </ul>
  </section>
  <body>
    {% with messages = get_flashed_messages() %} {% if messages %}
    <ul>
      {% for message in messages %}
      <li class="flash-msg">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %} {% block content %}{% endblock %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %} {% block title %}Home Page{% endblock %} {% block
content%}
<section class="hero">
  <h1>Welcome to PROFILYSER</h1>
  <p>
    Effortlessly find ideal candidates! Score applicants against job
    descriptions, save time, and build a high-performing team. Submit documents
    now!
  </p>
  <a href="{{ url_for('views.upload') }}" class="action-btn">Click to Begin</a>
</section>
{% endblock %}

templates/result.html
{% extends 'base.html' %} {% block title %}Result{% endblock %} {% block content
%}

<section class="result-section">
  <div class="result-title">Result</div>
  <div class="result-body">
    {% for candidate, score in candidate_scores.items() %}
    <div class="result-candidate">
      <div class="candidate">{{candidate}}</div>
      <div class="score">{{ score | round_to_decimal(2) }}</div>
    </div>
    {% endfor %}
  </div>
</section>

{% endblock %}

templates/upload.html
{% extends 'base.html' %} {% block title %}Upload Resumes{% endblock %} {% block
content %}
<section class="upload-section">
  <div class="upload-title">Rank your candidates</div>
  <form
    class="upload-form"
    id="upload-form"
    action="{{ url_for('views.upload') }}"
    method="post"
    enctype="multipart/form-data"
  >
    <label class="upload-form-textlabel" for="longText"
      >Enter or paste your job requirements:</label
    >
    <textarea
      class="upload-form-textarea"
      id="longText"
      name="longText"
      placeholder="Please enter your job requirements here..."
    ></textarea>

    <label class="upload-form-textlabel" for="longText"
      >Please choose your candidate files to upload (PDF only)</label
    >
    <input
      class="upload-form-file"
      id="upload-form-file"
      type="file"
      name="pdf_files"
      multiple
      accept=".pdf"
    />
    <input class="upload-form-submit" type="submit" value="Upload" />
  </form>
  <p class="upload-selected-file">Selected Files:</p>
  <ul id="fileList"></ul>
</section>

{% endblock %}